# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Point-Filter
version:      0.02
version_from: lib/GPS/Point/Filter.pm
installdirs:  site
requires:
    DateTime:                      0
    GPS::Point:                    0.11
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
